webhook:
  url: "http://example.com/api/receive"
  method: "POST"
  headers:
    Content-Type: "application/json"
  body: |
    {
      "event": "{{ Event }}",
      "user": "{{ User.Name }}",
      "description": "{{ Description }}",
      "server_version": "{{ Server.Version }}"
    }
webhook2:
  url: "http://example.com/api/another"
  method: "POST"
  headers:
    Content-Type: "application/json"
  body: |
    {
      "user": "{{ User.Name }}",
      "summary": "{{ Description }}"
    }
